# coding=utf-8
import unittest
import plugins
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
plugins.inject_plugin('auth', object())


class TestDefaultUserItems(unittest.TestCase):

    def setUp(self):
        pass

    def test_corpus_item_typ_readonly(self):
        """ test_corpus_item_typ_readonly """
        from mocks import manatee
        from plugins.ucnk_syntax_viewer import UcnkManateeBackend, UcnkTreeTemplate
        import plugins.default_syntax_viewer.manatee_backend as mbk

        parsed_data = [
            {u'afun': u'AuxS', u'word': u'#', u'id': u'root', u'parent': None},
            {'deepord': u'3', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Pred', 'functor': u'PAT', 'tag': u'NNFS4-----A----', 'ep_tag': u'VB-P---3P-AA---', 'caluse_number': u'1', 'antes': u'_', 'p_afun': u'Pred', 'grammatemes_rf': u'number=sg|typgroup=single|sempos=n.denot|gender=fem', 'lemma': u'jistota', 'p_lemma': u'd\xe1vat', 'afun': u'Obj', 'parent': u'+4', 'discourse_target': u'_', 'tfa': u'c', 'eparent': u'+4', 'coref_special': u'_', 'ord': u'1', 'p_tag': u'VB-P---3P-AA---', 'ep_lemma': u'd\xe1vat', 'p_form': u'd\xe1vaj\xed', 'word': u'Jistotu', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'd\xe1vaj\xed', 't_lemma': u'jistota'},
            {'deepord': u'2', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Obj', 'functor': u'REG', 'tag': u'RR--6----------', 'ep_tag': u'NNFS4-----A----', 'caluse_number': u'1', 'antes': u'_', 'p_afun': u'Obj', 'grammatemes_rf': u'gender=inan|sempos=n.denot|typgroup=single|number=sg', 'lemma': u'v', 'p_lemma': u'jistota', 'afun': u'AuxP', 'parent': u'-1', 'discourse_target': u'_', 'tfa': u't', 'eparent': u'-1', 'coref_special': u'segm', 'ord': u'2', 'p_tag': u'NNFS4-----A----', 'ep_lemma': u'jistota', 'p_form': u'Jistotu', 'word': u' v', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'aux', 'ep_form': u'Jistotu', 't_lemma': u'sm\u011br'},
            {'deepord': u'1', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'RSTR', 'tag': u'PDZS6----------', 'ep_tag': u'NNIS6-----A----', 'caluse_number': u'1', 'antes': u'_', 'p_afun': u'Atr', 'grammatemes_rf': u'sempos=adj.pron.def.demon', 'lemma': u'tento', 'p_lemma': u'sm\u011br', 'afun': u'Atr', 'parent': u'+1', 'discourse_target': u'_', 'tfa': u't', 'eparent': u'+1', 'coref_special': u'_', 'ord': u'3', 'p_tag': u'NNIS6-----A----', 'ep_lemma': u'sm\u011br', 'p_form': u'sm\u011bru', 'word': u' tomto', 'discourse_special': u'_', 'sempos': u'adj.pron.def.demon', 'a_type': u'lex', 'ep_form': u'sm\u011bru', 't_lemma': u'tento'},
            {'deepord': u'2', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'AuxP', 'functor': u'REG', 'tag': u'NNIS6-----A----', 'ep_tag': u'RR--6----------', 'caluse_number': u'1', 'antes': u'_', 'p_afun': u'AuxP', 'grammatemes_rf': u'gender=inan|sempos=n.denot|typgroup=single|number=sg', 'lemma': u'sm\u011br', 'p_lemma': u'v', 'afun': u'Atr', 'parent': u'-2', 'discourse_target': u'_', 'tfa': u't', 'eparent': u'-2', 'coref_special': u'segm', 'ord': u'4', 'p_tag': u'RR--6----------', 'ep_lemma': u'v', 'p_form': u'v', 'word': u' sm\u011bru', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'v', 't_lemma': u'sm\u011br'},
            {'deepord': u'4', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'AuxS', 'functor': u'PRED', 'tag': u'VB-P---3P-AA---', 'ep_tag': u'_', 'caluse_number': u'1', 'antes': u'_', 'p_afun': u'AuxS', 'grammatemes_rf': u'sempos=v|iterativeness=it0|tense=sim|aspect=proc|deontmod=decl', 'lemma': u'd\xe1vat', 'p_lemma': u'_', 'afun': u'Pred', 'parent': u'0', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'0', 'coref_special': u'_', 'ord': u'5', 'p_tag': u'_', 'ep_lemma': u'_', 'p_form': u'_', 'word': u' d\xe1vaj\xed', 'discourse_special': u'_', 'sempos': u'v', 'a_type': u'lex', 'ep_form': u'_', 't_lemma': u'd\xe1vat'},
            {'deepord': u'21', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Sb', 'functor': u'RSTR', 'tag': u'AAIP1----3A----', 'ep_tag': u'NNIP1-----A----', 'caluse_number': u'1', 'antes': u'_', 'p_afun': u'Sb', 'grammatemes_rf': u'degcmp=sup|negation=neg0|sempos=adj.denot', 'lemma': u'nov\xfd', 'p_lemma': u'krok', 'afun': u'Atr', 'parent': u'+1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'+1', 'coref_special': u'_', 'ord': u'6', 'p_tag': u'NNIP1-----A----', 'ep_lemma': u'krok', 'p_form': u'kroky', 'word': u' nejnov\u011bj\u0161\xed', 'discourse_special': u'_', 'sempos': u'adj.denot', 'a_type': u'lex', 'ep_form': u'kroky', 't_lemma': u'nov\xfd'},
            {'deepord': u'5', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Pred', 'functor': u'ACT', 'tag': u'NNIP1-----A----', 'ep_tag': u'VB-P---3P-AA---', 'caluse_number': u'1', 'antes': u'_', 'p_afun': u'Pred', 'grammatemes_rf': u'number=pl|typgroup=single|gender=inan|sempos=n.denot', 'lemma': u'krok', 'p_lemma': u'd\xe1vat', 'afun': u'Sb', 'parent': u'-2', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-2', 'coref_special': u'_', 'ord': u'7', 'p_tag': u'VB-P---3P-AA---', 'ep_lemma': u'd\xe1vat', 'p_form': u'd\xe1vaj\xed', 'word': u' kroky', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'd\xe1vaj\xed', 't_lemma': u'krok'},
            {'deepord': u'6', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Sb', 'functor': u'APP', 'tag': u'NNFS2-----A----', 'ep_tag': u'NNIP1-----A----', 'caluse_number': u'1', 'antes': u'tlemma=vl\xe1da|functor=APP', 'p_afun': u'Sb', 'grammatemes_rf': u'number=sg|gender=fem|sempos=n.denot|typgroup=single', 'lemma': u'vl\xe1da', 'p_lemma': u'krok', 'afun': u'Atr', 'parent': u'-1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-1', 'coref_special': u'_', 'ord': u'8', 'p_tag': u'NNIP1-----A----', 'ep_lemma': u'krok', 'p_form': u'kroky', 'word': u' vl\xe1dy', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'kroky', 't_lemma': u'vl\xe1da'},
            {'deepord': u'7', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'APP', 'tag': u'NNFXX-----A---8', 'ep_tag': u'NNFS2-----A----', 'caluse_number': u'1', 'antes': u'tlemma=SR|functor=ACT', 'p_afun': u'Atr', 'grammatemes_rf': u'number=sg|gender=fem|sempos=n.denot|typgroup=single', 'lemma': u'SR', 'p_lemma': u'vl\xe1da', 'afun': u'Atr', 'parent': u'-1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-1', 'coref_special': u'_', 'ord': u'9', 'p_tag': u'NNFS2-----A----', 'ep_lemma': u'vl\xe1da', 'p_form': u'vl\xe1dy', 'word': u' SR', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'vl\xe1dy', 't_lemma': u'SR'},
            {'deepord': u'_', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'_', 'tag': u'Z:-------------', 'ep_tag': u'VpQW---XR-AA--1', 'caluse_number': u'0', 'antes': u'_', 'p_afun': u'Atr', 'grammatemes_rf': u'_', 'lemma': u',', 'p_lemma': u'rozhodnout', 'afun': u'AuxX', 'parent': u'+3', 'discourse_target': u'_', 'tfa': u'_', 'eparent': u'+3', 'coref_special': u'_', 'ord': u'10', 'p_tag': u'VpQW---XR-AA--1', 'ep_lemma': u'rozhodnout', 'p_form': u'rozhodla', 'word': u' ,', 'discourse_special': u'_', 'sempos': u'_', 'a_type': u'null', 'ep_form': u'rozhodla', 't_lemma': u'_'},
            {'deepord': u'8', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'ACT', 'tag': u'P4FS1----------', 'ep_tag': u'VpQW---XR-AA--1', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Atr', 'grammatemes_rf': u'number=inher|indeftype=relat|person=inher|sempos=n.pron.indef|gender=inher', 'lemma': u'kter\xfd', 'p_lemma': u'rozhodnout', 'afun': u'Sb', 'parent': u'+2', 'discourse_target': u'_', 'tfa': u't', 'eparent': u'+2', 'coref_special': u'_', 'ord': u'11', 'p_tag': u'VpQW---XR-AA--1', 'ep_lemma': u'rozhodnout', 'p_form': u'rozhodla', 'word': u' kter\xe1', 'discourse_special': u'_', 'sempos': u'n.pron.indef', 'a_type': u'lex', 'ep_form': u'rozhodla', 't_lemma': u'kter\xfd'},
            {'deepord': u'9', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'RSTR', 'tag': u'P7-X4----------', 'ep_tag': u'VpQW---XR-AA--1', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Atr', 'grammatemes_rf': u'sempos=v|iterativeness=it0|deontmod=decl|tense=ant|aspect=cpl', 'lemma': u'se', 'p_lemma': u'rozhodnout', 'afun': u'AuxT', 'parent': u'+1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'+1', 'coref_special': u'_', 'ord': u'12', 'p_tag': u'VpQW---XR-AA--1', 'ep_lemma': u'rozhodnout', 'p_form': u'rozhodla', 'word': u' se', 'discourse_special': u'_', 'sempos': u'v', 'a_type': u'aux', 'ep_form': u'rozhodla', 't_lemma': u'rozhodnout_se'},
            {'deepord': u'9', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'RSTR', 'tag': u'VpQW---XR-AA--1', 'ep_tag': u'NNFS2-----A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Atr', 'grammatemes_rf': u'sempos=v|iterativeness=it0|deontmod=decl|tense=ant|aspect=cpl', 'lemma': u'rozhodnout', 'p_lemma': u'vl\xe1da', 'afun': u'Atr', 'parent': u'-5', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-5', 'coref_special': u'_', 'ord': u'13', 'p_tag': u'NNFS2-----A----', 'ep_lemma': u'vl\xe1da', 'p_form': u'vl\xe1dy', 'word': u' rozhodla', 'discourse_special': u'_', 'sempos': u'v', 'a_type': u'lex', 'ep_form': u'vl\xe1dy', 't_lemma': u'rozhodnout_se'},
            {'deepord': u'11', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'PAT', 'tag': u'Vf--------A----', 'ep_tag': u'VpQW---XR-AA--1', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Atr', 'grammatemes_rf': u'tense=nil|aspect=cpl|deontmod=decl|iterativeness=it0|sempos=v', 'lemma': u'zav\xe9st', 'p_lemma': u'rozhodnout', 'afun': u'Obj', 'parent': u'-1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-1', 'coref_special': u'_', 'ord': u'14', 'p_tag': u'VpQW---XR-AA--1', 'ep_lemma': u'rozhodnout', 'p_form': u'rozhodla', 'word': u' zav\xe9st', 'discourse_special': u'_', 'sempos': u'v', 'a_type': u'lex', 'ep_form': u'rozhodla', 't_lemma': u'zav\xe9st'},
            {'deepord': u'18', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Adv', 'functor': u'RHEM', 'tag': u'Db-------------', 'ep_tag': u'NNIS7-----A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Adv', 'grammatemes_rf': u'_', 'lemma': u'ji\u017e', 'p_lemma': u'\u010das', 'afun': u'AuxZ', 'parent': u'+2', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'+2', 'coref_special': u'_', 'ord': u'15', 'p_tag': u'NNIS7-----A----', 'ep_lemma': u'\u010das', 'p_form': u'\u010dasem', 'word': u' ji\u017e', 'discourse_special': u'_', 'sempos': u'_', 'a_type': u'lex', 'ep_form': u'\u010dasem', 't_lemma': u'ji\u017e'},
            {'deepord': u'19', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Obj', 'functor': u'TWHEN', 'tag': u'RR--7----------', 'ep_tag': u'Vf--------A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Obj', 'grammatemes_rf': u'gender=inan|sempos=n.denot|typgroup=single|number=sg', 'lemma': u'p\u0159ed', 'p_lemma': u'zav\xe9st', 'afun': u'AuxP', 'parent': u'-2', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-2', 'coref_special': u'_', 'ord': u'16', 'p_tag': u'Vf--------A----', 'ep_lemma': u'zav\xe9st', 'p_form': u'zav\xe9st', 'word': u' p\u0159ed', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'aux', 'ep_form': u'zav\xe9st', 't_lemma': u'\u010das'},
            {'deepord': u'19', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'AuxP', 'functor': u'TWHEN', 'tag': u'NNIS7-----A----', 'ep_tag': u'RR--7----------', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'AuxP', 'grammatemes_rf': u'gender=inan|sempos=n.denot|typgroup=single|number=sg', 'lemma': u'\u010das', 'p_lemma': u'p\u0159ed', 'afun': u'Adv', 'parent': u'-1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-1', 'coref_special': u'_', 'ord': u'17', 'p_tag': u'RR--7----------', 'ep_lemma': u'p\u0159ed', 'p_form': u'p\u0159ed', 'word': u' \u010dasem', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'p\u0159ed', 't_lemma': u'\u010das'},
            {'deepord': u'17', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Obj', 'functor': u'RSTR', 'tag': u'AAFS4----1A----', 'ep_tag': u'NNFS4-----A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Obj', 'grammatemes_rf': u'negation=neg0|degcmp=pos|sempos=adj.denot', 'lemma': u'avizovan\xfd', 'p_lemma': u'p\u0159ir\xe1\u017eka', 'afun': u'Atr', 'parent': u'+3', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'+3', 'coref_special': u'_', 'ord': u'18', 'p_tag': u'NNFS4-----A----', 'ep_lemma': u'p\u0159ir\xe1\u017eka', 'p_form': u'p\u0159ir\xe1\u017eku', 'word': u' avizovanou', 'discourse_special': u'_', 'sempos': u'adj.denot', 'a_type': u'lex', 'ep_form': u'p\u0159ir\xe1\u017eku', 't_lemma': u'avizovan\xfd'},
            {'deepord': u'20', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Obj', 'functor': u'RSTR', 'tag': u'AAFS4----1A----', 'ep_tag': u'NNFS4-----A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Obj', 'grammatemes_rf': u'degcmp=pos|negation=neg0|sempos=adj.denot', 'lemma': u'desetiprocentn\xed', 'p_lemma': u'p\u0159ir\xe1\u017eka', 'afun': u'Atr', 'parent': u'+2', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'+2', 'coref_special': u'_', 'ord': u'19', 'p_tag': u'NNFS4-----A----', 'ep_lemma': u'p\u0159ir\xe1\u017eka', 'p_form': u'p\u0159ir\xe1\u017eku', 'word': u' desetiprocentn\xed', 'discourse_special': u'_', 'sempos': u'adj.denot', 'a_type': u'lex', 'ep_form': u'p\u0159ir\xe1\u017eku', 't_lemma': u'desetiprocentn\xed'},
            {'deepord': u'13', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Obj', 'functor': u'RSTR', 'tag': u'AAFS4----1A----', 'ep_tag': u'NNFS4-----A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Obj', 'grammatemes_rf': u'sempos=adj.denot|degcmp=pos|negation=neg0', 'lemma': u'dovozn\xed', 'p_lemma': u'p\u0159ir\xe1\u017eka', 'afun': u'Atr', 'parent': u'+1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'+1', 'coref_special': u'_', 'ord': u'20', 'p_tag': u'NNFS4-----A----', 'ep_lemma': u'p\u0159ir\xe1\u017eka', 'p_form': u'p\u0159ir\xe1\u017eku', 'word': u' dovozn\xed', 'discourse_special': u'_', 'sempos': u'adj.denot', 'a_type': u'lex', 'ep_form': u'p\u0159ir\xe1\u017eku', 't_lemma': u'dovozn\xed'},
            {'deepord': u'12', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Obj', 'functor': u'PAT', 'tag': u'NNFS4-----A----', 'ep_tag': u'Vf--------A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Obj', 'grammatemes_rf': u'number=sg|typgroup=single|gender=fem|sempos=n.denot', 'lemma': u'p\u0159ir\xe1\u017eka', 'p_lemma': u'zav\xe9st', 'afun': u'Obj', 'parent': u'-7', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-7', 'coref_special': u'_', 'ord': u'21', 'p_tag': u'Vf--------A----', 'ep_lemma': u'zav\xe9st', 'p_form': u'zav\xe9st', 'word': u' p\u0159ir\xe1\u017eku', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'zav\xe9st', 't_lemma': u'p\u0159ir\xe1\u017eka'},
            {'deepord': u'14', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Obj', 'functor': u'PAT', 'tag': u'RR--4----------', 'ep_tag': u'NNFS4-----A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Obj', 'grammatemes_rf': u'gender=neut|sempos=n.denot|typgroup=single|number=sg', 'lemma': u'na', 'p_lemma': u'p\u0159ir\xe1\u017eka', 'afun': u'AuxP', 'parent': u'-1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-1', 'coref_special': u'_', 'ord': u'22', 'p_tag': u'NNFS4-----A----', 'ep_lemma': u'p\u0159ir\xe1\u017eka', 'p_form': u'p\u0159ir\xe1\u017eku', 'word': u' na', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'aux', 'ep_form': u'p\u0159ir\xe1\u017eku', 't_lemma': u'zbo\u017e\xed'},
            {'deepord': u'14', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'AuxP', 'functor': u'PAT', 'tag': u'NNNS4-----A----', 'ep_tag': u'RR--4----------', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'AuxP', 'grammatemes_rf': u'gender=neut|sempos=n.denot|typgroup=single|number=sg', 'lemma': u'zbo\u017e\xed', 'p_lemma': u'na', 'afun': u'Atr', 'parent': u'-1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-1', 'coref_special': u'_', 'ord': u'23', 'p_tag': u'RR--4----------', 'ep_lemma': u'na', 'p_form': u'na', 'word': u' zbo\u017e\xed', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'na', 't_lemma': u'zbo\u017e\xed'},
            {'deepord': u'16', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'RSTR', 'tag': u'AAFS2----1A----', 'ep_tag': u'NNFS2-----A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Atr', 'grammatemes_rf': u'sempos=adj.denot|negation=neg0|degcmp=pos', 'lemma': u'zahrani\u010dn\xed', 'p_lemma': u'provenience', 'afun': u'Atr', 'parent': u'+1', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'+1', 'coref_special': u'_', 'ord': u'24', 'p_tag': u'NNFS2-----A----', 'ep_lemma': u'provenience', 'p_form': u'provenience', 'word': u' zahrani\u010dn\xed', 'discourse_special': u'_', 'sempos': u'adj.denot', 'a_type': u'lex', 'ep_form': u'provenience', 't_lemma': u'zahrani\u010dn\xed'},
            {'deepord': u'15', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'Atr', 'functor': u'APP', 'tag': u'NNFS2-----A----', 'ep_tag': u'NNNS4-----A----', 'caluse_number': u'2', 'antes': u'_', 'p_afun': u'Atr', 'grammatemes_rf': u'number=sg|sempos=n.denot|gender=fem|typgroup=single', 'lemma': u'provenience', 'p_lemma': u'zbo\u017e\xed', 'afun': u'Atr', 'parent': u'-2', 'discourse_target': u'_', 'tfa': u'f', 'eparent': u'-2', 'coref_special': u'_', 'ord': u'25', 'p_tag': u'NNNS4-----A----', 'ep_lemma': u'zbo\u017e\xed', 'p_form': u'zbo\u017e\xed', 'word': u' provenience', 'discourse_special': u'_', 'sempos': u'n.denot', 'a_type': u'lex', 'ep_form': u'zbo\u017e\xed', 't_lemma': u'provenience'},
            {'deepord': u'_', 'discourse_type': u'_', 'is_member': u'_', 'ep_afun': u'AuxS', 'functor': u'_', 'tag': u'Z:-------------', 'ep_tag': u'_', 'caluse_number': u'0', 'antes': u'_', 'p_afun': u'AuxS', 'grammatemes_rf': u'_', 'lemma': u'.', 'p_lemma': u'_', 'afun': u'AuxK', 'parent': u'0', 'discourse_target': u'_', 'tfa': u'_', 'eparent': u'0', 'coref_special': u'_', 'ord': u'26', 'p_tag': u'_', 'ep_lemma': u'_', 'p_form': u'_', 'word': u' .', 'discourse_special': u'_', 'sempos': u'_', 'a_type': u'null', 'ep_form': u'_', 't_lemma': u'_'}
        ]

        conf = mbk.TreeConf({
                    "id": "default",
                    "name": "Default",
                    "wordAttr": "word",
                    "parentAttr": "parent",
                    "labelTemplates": ["#{#009EE0}%s", "#{#F0680B}[%s]", "#{#010101}%s", "#{#E2007A}%s"],
                    "layerType": "t",
                    "detailAttrs":  ['word', 'lemma', 'tag', 'ord'],
                    "attrRefs": {
                        "eparent": ["word"]
                    },
                    "nodeAttrs": ["word", "afun"],
                    "rootNode": {
                        "id": "root",
                        "word": "#",
                        "afun": "AuxS",
                        "parent": None
                    }
                })

        conf.all_attrs = ['word', 'lemma', 'tag', 'ord', 'caluse_number', 'is_member', 'afun', 'a_type', 'deepord', 't_lemma', 'functor', 'tfa', 'sempos', 'grammatemes_rf', 'coref_special', 'antes', 'discourse_special', 'discourse_type', 'discourse_target', 'parent', 'eparent', 'p_form', 'p_lemma', 'p_tag', 'p_afun', 'ep_form', 'ep_lemma', 'ep_tag', 'ep_afun']
        umb = UcnkManateeBackend({})
        umb._decode_tree_data(parsed_data, "parent", conf.attr_refs)
        tb = mbk.TreeBuilder()
        tree_data = tb.process(conf, parsed_data)
        kwic_pos = (29, 1)
        template = UcnkTreeTemplate("default", tree_data, kwic_pos, {"default": conf})
        data, encoder = template.export(), mbk.TreeNodeEncoder
        print json.dumps(data, cls=encoder)


if __name__ == '__main__':
    unittest.main()
