version: '2'
services:
    kontext:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/opt/kontext/installation/
            - .:/opt/kontext/log/
            - ../lindat-test-corpora:/opt/lindat/lindat-test-corpora
            - ../lindat-test-corpora/registry:/opt/kontext/data/registry
        links:
            - redis
    redis:
        image: "redis:alpine"    
